/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmBox: typeof import('./src/components/custom/ConfirmBox.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputPro: typeof import('./src/components/custom/ElInputPro/ElInputPro.vue')['default']
    ElMessageBoxPro: typeof import('./src/components/custom/ElMessageBoxPro/ElMessageBoxPro.vue')['default']
    ElMessageBoxProView: typeof import('./src/components/custom/ElMessageBoxPro/ElMessageBoxProView.vue')['default']
    ElWatermark: typeof import('element-plus/es')['ElWatermark']
    Example: typeof import('./src/components/scaleScreen/example.vue')['default']
    MessageDialog: typeof import('./src/components/custom/ElMessageBoxPro/MessageDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleScreen: typeof import('./src/components/scaleScreen/scaleScreen.vue')['default']
    ScreenAdapter: typeof import('./src/components/ScreenAdapter/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle/ThemeToggle.vue')['default']
  }
}
